from enum import StrEnum

class TLEGroup(StrEnum):
    # Special interest
    LAST_30_DAYS = "last-30-days"
    STATIONS = "stations"
    VISUAL = "visual"
    ACTIVE = "active"
    ANALYST = "analyst"
    # Debris
    FENGYUN_1C_DEBRIS = "fengyun-1c-debris"
    IRIDIUM_33_DEBRIS = "iridium-33-debris"
    COSMOS_2251_DEBRIS = "cosmos-2251-debris"
    # Weather & Earth Resources
    WEATHER = "weather"
    RESOURCE = "resource"
    SARSAT = "sarsat"
    DMC = "dmc"
    TDRSS = "tdrss"
    ARGOS = "argos"
    PLANET = "planet"
    SPIRE = "spire"
    # Communications
    GEO = "geo"
    INTELSAT = "intelsat"
    SES = "ses"
    EUTELSAT = "eutelsat"
    TELESAT = "telesat"
    STARLINK = "starlink"
    ONEWEB = "oneweb"
    QIANFAN = "qianfan"
    HULIANWANG = "hulianwang"
    KUIPER = "kuiper"
    IRIDIUM_NEXT = "iridium-NEXT"
    ORBCOMM = "orbcomm"
    GLOBALSTAR = "globalstar"
    AMATEUR = "amateur"
    SATNOGS = "satnogs"
    X_COMM = "x-comm"
    OTHER_COMM = "other-comm"
    # Navigation
    GNSS = "gnss"
    GPS_OPS = "gps-ops"
    GLO_OPS = "glo-ops"
    GALILEO = "galileo"
    BEIDOU = "beidou"
    SBAS = "sbas"
    NNSS = "nnss"
    MUSSON = "musson"
    # Science
    SCIENCE = "science"
    GEODETIC = "geodetic"
    ENGINEERING = "engineering"
    EDUCATION = "education"
    # Misc
    MILITARY = "military"
    RADAR = "radar"
    CUBESAT = "cubesat"
    OTHER = "other"